### ISSUE TITLE
Custom CA for ldaps

### ISSUE THREAD

**Issue by git001** [hashicorp/vault-plugin-secrets-openldap#8]
Most enterprise environment requires there own CA.  
Please can you add a *tls* section to the config to be able to add custom TLS Paramters as the library support the [tls.Config](https://golang.org/pkg/crypto/tls/#Config) https://github.com/go-ldap/ldap/issues/180#issuecomment-412876869

**Comment by jasonodonnell** [comment]
Hi @git001, there is already a configurable for custom CA. See the `certificate` parameter here: https://www.vaultproject.io/api-docs/secret/openldap#parameters.

**Comment by jasonodonnell** [comment]
Upon further review there are other undocumented TLS parameters (I can add them):

https://github.com/hashicorp/vault/blob/961ea1e0bbd9e4308410f7558654232bea158580/sdk/helper/ldaputil/config.go#L123

https://github.com/hashicorp/vault/blob/961ea1e0bbd9e4308410f7558654232bea158580/sdk/helper/ldaputil/config.go#L132

**Comment by git001** [comment]
@jasonodonnell cool, thanks for your answer.  
It would be great when the other TLS paramters are also documented.

**Comment by jasonodonnell** [comment]
@git001 Doc added in this PR: https://github.com/hashicorp/vault/pull/8730

It should be live on the website in a few minutes.  Closing this!
