### ISSUE TITLE
rotate-root must have secure option to store hashed userPassword

### ISSUE THREAD

**Issue by avoidik** [hashicorp/vault-plugin-secrets-openldap#9]
Hello,

for example, no matter how initial root password had been created a call to a `rotate-root` converts it into the plain-text password, therefore it could be possible to read newly generated password.

On the picture below you may see the root user password in plain-text after the rotation had been performed by Vault with the call to `openldap/rotate-root` API endpoint

![image](https://user-images.githubusercontent.com/6435932/80864254-29083280-8c8a-11ea-81e5-1e9bb9da4d87.png)

There is a option supported by OpenLDAP itself to store password hashes like SSHA, SHA512, and others per RFC 2307. So I see it could be implemented as additional parameter to the `rotate-root` API method, something like `password_type` and list of options `SSHA`, `SHA`, etc.

```
vault write -f openldap/rotate-root password_type='SSHA'
```

And if not specified it must be secure by default, e.g. `SSHA`.

Thank you!

**Comment by avoidik** [comment]
It looks like the same improvement also required for `static-role`, or perhaps I didn't get the security model behind this plugin.

**Comment by jasonodonnell** [comment]
Hi @avoidik, I've [opened a PR](https://github.com/hashicorp/vault/pull/9856) to the Vault website to add a note about this.  We suggest using a `ppolicy` to enforce hashing by the LDAP server.  In the future we hope to support client side hashing/encryption.
